require("keymappings")
require("options")
require("plugins")
require("nvim-compe-cfg")
require("nvim-tree-cfg")
require('lsp')
require('lsp.lua-ls')
-- require("./lua/keymappings")
-- require("./lua/keymappings")
-- require("./lua/keymappings")
